# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/NotExist/PrivateSpecs.git'

target 'RenovateTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RenovateTest

  target 'RenovateTestTests' do
    inherit! :search_paths
    pod 'Quick', '3.1.2'
    # Pods for testing
  end

  target 'RenovateTestUITests' do
    # Pods for testing
  end

end
