# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://cdn.cocoapods.org/'
# source 'https://github.com/NotExistRepo/PrivateSpecs.git'
platform :ios, '12.0'

target 'RenovateTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RenovateTest
  pod 'AttachmentInput', '0.0.4' 

  target 'RenovateTestTests' do
    inherit! :search_paths
    pod 'Quick', '3.1.2'
    pod 'Nimble', '9.0.0' 
    pod 'RxTest', '6.1.0'  
    # Pods for testing
  end

  target 'RenovateTestUITests' do
    # Pods for testing
  end

end
